### ISSUE TITLE
inquiry

### ISSUE THREAD

**Issue by emekalites** [muhzi4u/URL-Shortner#4]
Hi, nice project you got going here, will want to use it but any chance you'll add more code to the project especially those from your todo:
* Add Redis for caching
* Change short code algorithm and check duplicate short codes

**Comment by muhsin-k** [comment]
Hi @emekalites, 
* Added the Redis caching service
* For finding the duplicates, just add another DB call to check duplicate short codes. That's all.

Please pull the latest code from the master. If you have any doubt please let me know. Thanks

**Comment by emekalites** [comment]
Thanks
